---
repos:
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.0.258
      hooks:
          - id: ruff

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-yaml
          - id: check-json
          - id: pretty-format-json
            args: [--autofix, --indent, '4', --no-sort-keys]
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-merge-conflict
          - id: debug-statements
          - id: check-docstring-first

    - repo: https://github.com/psf/black
      rev: 23.1.0
      hooks:
          - id: black
            language_version: python3.11
